# Generated by Django 3.0.5 on 2022-03-17 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APP_gestion_livres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='abonne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pret',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='APP_gestion_livres.Livre'),
        ),
        migrations.AddField(
            model_name='livre',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='APP_gestion_livres.Auteur'),
        ),
        migrations.AddField(
            model_name='livre',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='APP_gestion_livres.Categorie'),
        ),
        migrations.AddField(
            model_name='auteur',
            name='nationalite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='APP_gestion_livres.nationalite'),
        ),
    ]
